### ISSUE TITLE
rename script in ioBroker Admin, old file still exist

### ISSUE THREAD

**Issue by truegreyhound** [iobroker-community-adapters/ioBroker.js2fs-community#14]
I renamed a script in the admin UI, then I had the new and the old script in the admin and in the file system. The renaming worked fine with some other scripts. Unfortunately I couldn't see any differences in my actions.

ioBroker.js-controller: 2.1.1
ioBroker.js2fs: 0.1.5
node.js: 10.17
OS: Win10 1909

**Comment by Apollon77** [comment]
Do you have tried javascript 4.3 with mirroring functionality? Maybe we better drive this and phase out this adapter?

**Comment by truegreyhound** [comment]
script engine 4.3.4
Admin 3.7.2

Why phase out? What are the alternatives? You can deal with this mistake if you know it.

**Comment by Apollon77** [comment]
As I wrote: the JavaScript adapter itself got a mirroring to filesystem Feature in 4.3. 

We should try this ;-)

I personally also use js2fs but beside bugs like you found Lao object timestamps are not fully supported.

**Comment by truegreyhound** [comment]
okay, I will test. I only found it on the configuration page after you were informed again. Thank you

With VC I created a new file in a script subdirectory. The file was imported correctly by the Java script adapter into ioBroker as a type script. 

Then I renamed the file in ioBroker UI. A short time later "the old file" was back. Certainly you the synchronization from the file system. Both files can also be seen in VC. After deleting the old file in ioBroker, everything is fine again.

I think that's due to the underlying mechanism and not a bug.

But how do you control that with the
/// <reference path = "../ javascript.d.ts" />
So that VC also finds this file. Are * .d.ts files excluded from synchronization?
see #16

**Comment by Apollon77** [comment]
Effects you described were with JavaScript adapter? Then ipen Issue there too?

**Comment by truegreyhound** [comment]
I will close the issue here, a corresponding issue already exists under JavaScript adapter #451
